"""Sweep all agent transcripts on this machine and build a corruption leaderboard.

Usage: python scripts/sweep.py [--out leaderboard.md]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from trustleash.adapters import audit_transcript  # noqa: E402

HOME = Path.home()

SCAN_GLOBS = {
    "gemini": sorted(HOME.glob(".gemini/tmp/*/chats/*.jsonl")),
    "codex": sorted(HOME.glob(".codex/sessions/*/*/*/rollout-*.jsonl")),
    "claude": sorted(HOME.glob(".claude/projects/*/*.jsonl")),
    "opencode": [p for p in HOME.glob(".local/share/opencode/storage/message/*")
                 if p.is_dir()],
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=None, help="write markdown leaderboard here")
    args = ap.parse_args()

    rows = []
    for agent, paths in SCAN_GLOBS.items():
        for path in paths:
            try:
                result, fmt = audit_transcript(path, root=HOME)
            except Exception as e:  # unreadable transcript: count as errored
                rows.append((agent, path.name, "ERROR", 0, 0, 0, 0, str(e)[:60]))
                continue
            rows.append((
                agent,
                path.name[:44],
                result.verdict,
                result.messages,
                result.tool_calls,
                len(result.claimed_paths),
                len(result.phantom_paths),
                result.register.corruption_score,
            ))

    order = {"CORRUPT": 0, "WAVERING": 1, "CLEAN": 2, "ERROR": 3}
    rows.sort(key=lambda r: (order.get(r[2], 4), -(r[6]), -(r[7])))

    lines = [
        "# Agent Corruption Leaderboard",
        "",
        f"Generated by TrustLeash sweep — {len(rows)} sessions audited.",
        "",
        "| Agent | Session | Verdict | Msgs | Tools | Claims | Phantoms | Corr. score |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        icon = {"CORRUPT": "❌", "WAVERING": "⚠️", "CLEAN": "✅", "ERROR": "💥"}.get(r[2], "")
        lines.append(
            f"| {r[0]} | `{r[1]}` | {icon} {r[2]} | {r[3]} | {r[4]} | {r[5]} | {r[6]} | {r[7]:.4f} |"
        )

    # summary
    by_agent: dict[str, list] = {}
    for r in rows:
        by_agent.setdefault(r[0], []).append(r)
    lines += ["", "## Per-agent summary", "",
              "| Agent | Sessions | CORRUPT | WAVERING | CLEAN | Phantom claims |", "|---|---|---|---|---|---|"]
    for agent, rs in sorted(by_agent.items()):
        lines.append(
            f"| {agent} | {len(rs)} | "
            f"{sum(1 for r in rs if r[2] == 'CORRUPT')} | "
            f"{sum(1 for r in rs if r[2] == 'WAVERING')} | "
            f"{sum(1 for r in rs if r[2] == 'CLEAN')} | "
            f"{sum(r[6] for r in rs)} |"
        )

    report = "\n".join(lines) + "\n"
    print(report)

    if args.out:
        Path(args.out).write_text(report, encoding="utf-8")
        print(f"written to {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
